name = "time-seal"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "timeseal-db"
database_id = "4b0ca768-e38b-400b-8601-e6ebd34a1734"
