name = "time-seal"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[env.production]
name = "time-seal"

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "timeseal-vault"

[[env.production.d1_databases]]
binding = "DB"
database_name = "timeseal-db"
database_id = "YOUR_DATABASE_ID"
